repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--check]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.401
    hooks:
      - id: pyright