import * as vscode from "vscode";
import { editPolicyFor, type RGWBundle } from "../rgwIo";

const path = require("path");
const fs = require("fs");

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * JSON-encode a state object for embedding inside `<script>...</script>`.
 * Escapes `<`, `>`, and U+2028/U+2029 so the literal can't break out of the
 * script tag (a requirement title containing `</script>` would otherwise
 * terminate the block early). The output remains valid JSON.
 */
function serializeStateForScriptTag(state: unknown): string {
  return JSON.stringify(state)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

/**
 * Replace every `{{key}}` placeholder in `html` with the matching value. Uses
 * a replacer function so `$` sequences in values (paths, JSON) aren't
 * interpreted as String.replace special patterns.
 */
function fillTemplate(html: string, values: Record<string, string>): string {
  return html.replace(/{{\s*(\w+)\s*}}/g, (match, key) =>
    Object.prototype.hasOwnProperty.call(values, key) ? values[key] : match
  );
}

/**
 * Build the full webview HTML. The static skeleton lives in
 * `webviews/html/requirements.html` (loaded from disk, mirroring the layout
 * under `manage/webviews`); this fills in its `{{...}}` placeholders. CSS + JS
 * are referenced through webview-relative URIs (a generated nonce gates
 * `<script>` execution). Initial state is injected as a `window.__rgwState`
 * blob the script picks up on load and renders into the empty `#reqs-body` via
 * safe DOM APIs — there's no server-side card rendering anymore, so every
 * concrete element comes from one place (the JS).
 */
export function generateRequirementsHtml(
  webview: vscode.Webview,
  webviewBaseDir: string,
  nonce: string,
  bundle: RGWBundle,
  unitsToFunctions: Record<string, string[]> | null = null,
  onlyUntracedSupported = false
): string {
  const policy = editPolicyFor(bundle);

  const cssUri = webview.asWebviewUri(
    vscode.Uri.file(path.join(webviewBaseDir, "css", "requirements.css"))
  );
  const scriptUri = webview.asWebviewUri(
    vscode.Uri.file(
      path.join(webviewBaseDir, "webviewScripts", "requirements.js")
    )
  );

  const bannerHtml = policy.bodiesEditable
    ? `<div class="banner banner-editable">Editable — these requirements were generated by Reqs2X. Changes are saved back into the RGW.</div>`
    : `<div class="banner banner-readonly">Only traceability information can be updated with requirements exported from an external source (Polarion, DOORS, ...). Otherwise re-import could conflict with local changes.</div>`;

  const initialState = {
    gatewayPath: bundle.gatewayPath,
    policy,
    mtimes: bundle.mtimes,
    requirements: bundle.requirements,
    traceability: bundle.traceability,
    unitsToFunctions,
    onlyUntracedSupported,
  };

  // Split button when --only-untraced is supported (default = untraced only,
  // caret reveals "re-infer everything"); plain full-infer button otherwise.
  const inferHtml = onlyUntracedSupported
    ? `<div id="infer-group" class="split-btn">` +
      `<button id="infer-btn" class="toolbar-btn" title="Use the configured LLM to infer the unit/function only for requirements missing one. Already-traced requirements are left unchanged.">✨ Infer traceability</button>` +
      `<button id="infer-caret" class="toolbar-btn split-caret" title="More infer options" aria-haspopup="true" aria-expanded="false">▾</button>` +
      `<div id="infer-menu" class="split-menu" role="menu" hidden>` +
      `<button class="infer-menu-item" role="menuitem" tabindex="-1" data-only-untraced="true" title="Use the configured LLM to infer the unit/function only for requirements missing one. Already-traced requirements are left unchanged.">Infer untraced only</button>` +
      `<button class="infer-menu-item" role="menuitem" tabindex="-1" data-only-untraced="false" title="Use the configured LLM to re-infer the unit/function for every requirement, overwriting any existing traceability.">Re-infer everything</button>` +
      `</div></div>`
    : `<button id="infer-btn" class="toolbar-btn" title="Use the configured LLM to infer the unit/function each requirement traces to.">✨ Infer traceability</button>`;

  const addHtml = policy.bodiesEditable
    ? `<button id="add-btn" class="toolbar-btn" title="Add a new requirement to this RGW.">+ Add requirement</button>`
    : "";
  const toolbarHtml = `${addHtml}${inferHtml}<button id="save-btn" class="toolbar-btn" disabled>Save changes</button>`;

  const cspSource = webview.cspSource;
  const cspMeta = `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${cspSource}; script-src 'nonce-${nonce}' ${cspSource};">`;

  const htmlPath = path.join(webviewBaseDir, "html", "requirements.html");
  const template = fs.readFileSync(htmlPath, "utf8");

  return fillTemplate(template.replace(/<head>/, `<head>${cspMeta}`), {
    cssUri: cssUri.toString(),
    scriptUri: scriptUri.toString(),
    nonce,
    gatewayPath: escapeHtml(bundle.gatewayPath),
    banner: bannerHtml,
    toolbar: toolbarHtml,
    stateJson: serializeStateForScriptTag(initialState),
  });
}
