-- VectorCAST 6.0 (%H%)
-- Test Case Script
-- 
-- Environment    : CSV_EXAMPLE
-- Unit(s) Under Test: line
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
--

-- Unit: line

-- Subprogram: findY

-- Test Case: (MAP)FINDY.001
TEST.UNIT:line
TEST.SUBPROGRAM:findY
TEST.NEW
TEST.NAME:(MAP)FINDY.001
TEST.CSV_FILENAME:$(VECTORCAST_DIR)/examples/c/csv_example/table.csv
TEST.CSV_DELIMITER:COMMA
TEST.CSV_HEADER_ROWS: 1
TEST.CSV_ROWS_PER_TESTCASE: 1
TEST.CSV_COLUMN_INFO: 3, TEST.VALUE:line.findY.x
TEST.CSV_COLUMN_INFO: 2, TEST.VALUE:line.findY.m
TEST.CSV_COLUMN_INFO: 4, TEST.VALUE:line.findY.b
TEST.CSV_COLUMN_INFO: 1, TEST.EXPECTED:line.findY.return
TEST.END
