import * as vscode from "vscode";
import { editPolicyFor, type RGWBundle } from "../rgwIo";

const path = require("path");

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * JSON-encode a state object for embedding inside `<script>...</script>`.
 * Escapes `<`, `>`, and U+2028/U+2029 so the literal can't break out of the
 * script tag (a requirement title containing `</script>` would otherwise
 * terminate the block early). The output remains valid JSON.
 */
function serializeStateForScriptTag(state: unknown): string {
  return JSON.stringify(state)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

/**
 * Build the full webview HTML. Loads CSS + JS from the `webviews/` media
 * folder via webview-relative URIs (a generated nonce gates `<script>`
 * execution). Initial state is injected as a `window.__rgwState` blob the
 * script picks up on load and renders into the empty `#reqs-body` via
 * safe DOM APIs — there's no server-side card rendering anymore, so every
 * concrete element comes from one place (the JS).
 */
export function generateRequirementsHtml(
  webview: vscode.Webview,
  webviewBaseDir: string,
  nonce: string,
  bundle: RGWBundle,
  unitsToFunctions: Record<string, string[]> | null = null,
  onlyUntracedSupported = false,
  reqs2checkAvailable = false
): string {
  const policy = editPolicyFor(bundle);

  const cssUri = webview.asWebviewUri(
    vscode.Uri.file(path.join(webviewBaseDir, "css", "requirements.css"))
  );
  const scriptUri = webview.asWebviewUri(
    vscode.Uri.file(
      path.join(webviewBaseDir, "webviewScripts", "requirements.js")
    )
  );

  const bannerHtml = policy.bodiesEditable
    ? `<div class="banner banner-editable">Editable — these requirements were generated by Reqs2X. Changes are saved back into the RGW.</div>`
    : `<div class="banner banner-readonly">Only traceability information can be updated with requirements exported from an external source (Polarion, DOORS, ...). Otherwise re-import could conflict with local changes.</div>`;

  const initialState = {
    gatewayPath: bundle.gatewayPath,
    policy,
    mtimes: bundle.mtimes,
    requirements: bundle.requirements,
    traceability: bundle.traceability,
    unitsToFunctions,
    onlyUntracedSupported,
  };

  // Split button when --only-untraced is supported (default = untraced only,
  // caret reveals "re-infer everything"); plain full-infer button otherwise.
  const inferHtml = onlyUntracedSupported
    ? `<div id="infer-group" class="split-btn">` +
      `<button id="infer-btn" class="toolbar-btn" title="Use the configured LLM to infer the unit/function only for requirements missing one. Already-traced requirements are left unchanged.">✨ Infer traceability</button>` +
      `<button id="infer-caret" class="toolbar-btn split-caret" title="More infer options" aria-haspopup="true" aria-expanded="false">▾</button>` +
      `<div id="infer-menu" class="split-menu" role="menu" hidden>` +
      `<button class="infer-menu-item" role="menuitem" tabindex="-1" data-only-untraced="true" title="Use the configured LLM to infer the unit/function only for requirements missing one. Already-traced requirements are left unchanged.">Infer untraced only</button>` +
      `<button class="infer-menu-item" role="menuitem" tabindex="-1" data-only-untraced="false" title="Use the configured LLM to re-infer the unit/function for every requirement, overwriting any existing traceability.">Re-infer everything</button>` +
      `</div></div>`
    : `<button id="infer-btn" class="toolbar-btn" title="Use the configured LLM to infer the unit/function each requirement traces to.">✨ Infer traceability</button>`;

  const cspSource = webview.cspSource;
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${cspSource}; script-src 'nonce-${nonce}' ${cspSource};">
<title>Requirements</title>
<link rel="stylesheet" href="${cssUri}">
</head>
<body>
<h1>Requirements</h1>
<div id="rgw-pill" title="${escapeHtml(bundle.gatewayPath)}">RGW: ${escapeHtml(bundle.gatewayPath)}</div>
${bannerHtml}
<div id="save-toolbar">${policy.bodiesEditable ? `<button id="add-btn" class="toolbar-btn" title="Add a new requirement to this RGW.">+ Add requirement</button>` : ""}${inferHtml}<button id="generate-tests-btn" class="toolbar-btn" title="Use the configured LLM to generate VectorCAST tests for these requirements.">✨ Generate tests</button>${reqs2checkAvailable ? `<button id="verify-btn" class="toolbar-btn" title="Use the configured LLM to compare every requirement against the code, surfacing violations and undocumented behaviour in a verification report.">✨ Compare requirements against code</button>` : ""}<button id="save-btn" class="toolbar-btn" disabled>Save changes</button></div>
<div id="search-bar"><input id="search-input" type="search" placeholder="Search…" /><select id="filter-unit" title="Filter by unit"></select><select id="filter-function" title="Filter by function"></select><span id="search-count"></span></div>
<div id="reqs-body"></div>
<script nonce="${nonce}">window.__rgwState = ${serializeStateForScriptTag(initialState)};</script>
<script nonce="${nonce}" type="module" src="${scriptUri}"></script>
</body>
</html>`;
}
