import * as vscode from "vscode";
import {
  editPolicyFor,
  type RGWBundle,
  type RGWRequirement,
  type RGWTraceabilityEntry,
} from "../rgwIo";

const path = require("path");

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * JSON-encode a state object for embedding inside `<script>...</script>`.
 * Escapes `<`, `>`, and U+2028/U+2029 so the literal can't break out of the
 * script tag (a requirement title containing `</script>` would otherwise
 * terminate the block early). The output remains valid JSON.
 */
function serializeStateForScriptTag(state: unknown): string {
  return JSON.stringify(state)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

/**
 * Render the grouped headings + cards for a bundle. Exported so the extension
 * can call it again after save/infer to refresh the headings — they reflect
 * the current `function || unit || source` grouping, which can change as the
 * user edits traceability.
 */
export function renderRequirementsBody(
  bundle: RGWBundle,
  unitsToFunctions: Record<string, string[]> | null
): string {
  const policy = editPolicyFor(bundle);

  const flat: Array<{
    source: string;
    id: string;
    req: RGWRequirement;
    trace: RGWTraceabilityEntry;
  }> = [];
  for (const [source, bucket] of Object.entries(bundle.requirements)) {
    for (const [id, req] of Object.entries(bucket)) {
      flat.push({
        source,
        id,
        req,
        trace: bundle.traceability[id] ?? {
          unit: null,
          function: null,
          lines: null,
        },
      });
    }
  }

  // Group by function, falling back to unit, then source.
  const groups: Record<string, typeof flat> = {};
  for (const entry of flat) {
    const key =
      entry.trace.function || entry.trace.unit || entry.source || "Unknown";
    if (!groups[key]) groups[key] = [];
    groups[key].push(entry);
  }

  let body = "";
  for (const [group, entries] of Object.entries(groups)) {
    body += `<h2>${escapeHtml(group)}</h2>`;
    for (const entry of entries) {
      body += renderCard(entry, policy.bodiesEditable, unitsToFunctions);
    }
  }
  return body;
}

/**
 * Build the full webview HTML. Loads CSS + JS from the `webviews/` media
 * folder via webview-relative URIs (a generated nonce gates `<script>`
 * execution). Initial state is injected as a `window.__rgwState` blob the
 * script picks up on load.
 */
export function generateRequirementsHtml(
  webview: vscode.Webview,
  webviewBaseDir: string,
  nonce: string,
  bundle: RGWBundle,
  unitsToFunctions: Record<string, string[]> | null = null
): string {
  const policy = editPolicyFor(bundle);

  const cssUri = webview.asWebviewUri(
    vscode.Uri.file(path.join(webviewBaseDir, "css", "requirements.css"))
  );
  const scriptUri = webview.asWebviewUri(
    vscode.Uri.file(
      path.join(webviewBaseDir, "webviewScripts", "requirements.js")
    )
  );

  const bannerHtml = policy.bodiesEditable
    ? `<div class="banner banner-editable">Editable — these requirements were generated by Reqs2X. Changes are saved back into the RGW.</div>`
    : `<div class="banner banner-readonly">Only traceability information can be updated with requirements exported from an external source (Polarion, DOORS, ...). Otherwise re-import could conflict with local changes.</div>`;

  const body = renderRequirementsBody(bundle, unitsToFunctions);

  const initialState = {
    gatewayPath: bundle.gatewayPath,
    policy,
    mtimes: bundle.mtimes,
    requirements: bundle.requirements,
    traceability: bundle.traceability,
    unitsToFunctions,
  };

  const cspSource = webview.cspSource;
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${cspSource}; script-src 'nonce-${nonce}';">
<title>Requirements</title>
<link rel="stylesheet" href="${cssUri}">
</head>
<body>
<h1>Requirements</h1>
<div id="rgw-pill" title="${escapeHtml(bundle.gatewayPath)}">RGW: ${escapeHtml(bundle.gatewayPath)}</div>
${bannerHtml}
<div id="save-toolbar"><button id="infer-btn" title="Use the configured LLM to infer the unit/function each requirement traces to.">✨ Infer traceability</button><button id="save-btn" disabled>Save changes</button></div>
<div id="reqs-body">${body}</div>
<script nonce="${nonce}">window.__rgwState = ${serializeStateForScriptTag(initialState)};</script>
<script nonce="${nonce}" src="${scriptUri}"></script>
</body>
</html>`;
}

function renderCard(
  entry: {
    source: string;
    id: string;
    req: RGWRequirement;
    trace: RGWTraceabilityEntry;
  },
  editable: boolean,
  unitsToFunctions: Record<string, string[]> | null
): string {
  const idAttrs = `data-req-id="${escapeHtml(entry.id)}"`;
  const reqDis = editable ? "" : "disabled";
  const lastMod = entry.req.last_modified ?? "";

  return `
    <div class="req">
      <div class="req-header">
        <div class="req-id">${escapeHtml(entry.id)}</div>
        <div class="req-meta">${lastMod ? `modified: ${escapeHtml(lastMod)} · ` : ""}source: ${escapeHtml(entry.source)}</div>
      </div>
      <div class="field">
        <label>Title</label>
        <input type="text" ${idAttrs} data-scope="req" data-field="title" value="${escapeHtml(entry.req.title ?? "")}" ${reqDis}>
      </div>
      <div class="field">
        <label>Description</label>
        <textarea ${idAttrs} data-scope="req" data-field="description" ${reqDis}>${escapeHtml(entry.req.description ?? "")}</textarea>
      </div>
      <div class="field trace-row">
        <div>
          <label>Traceability: unit</label>
          ${renderTraceField({
            field: "unit",
            current: entry.trace.unit ?? "",
            options: unitsToFunctions ? Object.keys(unitsToFunctions) : null,
            idAttrs,
          })}
        </div>
        <div>
          <label>Traceability: function</label>
          ${renderTraceField({
            field: "function",
            current: entry.trace.function ?? "",
            options: unitsToFunctions
              ? unitsToFunctions[entry.trace.unit ?? ""] ?? []
              : null,
            idAttrs,
          })}
        </div>
      </div>
    </div>
  `;
}

/**
 * Render a traceability field as either a free-text input (when `options` is
 * null — env data wasn't available) or a `<select>` dropdown with a "(none)"
 * entry. Preserves the current value as a synthetic "(not in env)" option if
 * it falls outside the known set, so legacy/stale data isn't silently dropped.
 */
function renderTraceField(args: {
  field: "unit" | "function";
  current: string;
  options: string[] | null;
  idAttrs: string;
}): string {
  const { field, current, options, idAttrs } = args;
  if (!options) {
    return `<input type="text" ${idAttrs} data-scope="trace" data-field="${field}" value="${escapeHtml(current)}">`;
  }
  const opts = [
    `<option value=""${current === "" ? " selected" : ""}>(none)</option>`,
  ];
  let found = current === "";
  for (const o of options) {
    const sel = o === current ? " selected" : "";
    if (o === current) found = true;
    opts.push(`<option value="${escapeHtml(o)}"${sel}>${escapeHtml(o)}</option>`);
  }
  if (!found) {
    opts.push(
      `<option value="${escapeHtml(current)}" selected>${escapeHtml(current)} (not in env)</option>`
    );
  }
  return `<select ${idAttrs} data-scope="trace" data-field="${field}">${opts.join("")}</select>`;
}

