-- VectorCAST 6.4s (05/01/17)
-- Test Case Script
-- Environment    : TUTORIAL_C
-- Unit(s) Under Test: manager
-- 
-- Script Features
TEST.SCRIPT_FEATURE:C_DIRECT_ARRAY_INDEXING
TEST.SCRIPT_FEATURE:CPP_CLASS_OBJECT_REVISION
TEST.SCRIPT_FEATURE:MULTIPLE_UUT_SUPPORT
TEST.SCRIPT_FEATURE:MIXED_CASE_NAMES
TEST.SCRIPT_FEATURE:STATIC_HEADER_FUNCS_IN_UUTS

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:No_Free_Dessert_For_Non_Qualifying_Order-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR27
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that Add_Included_Dessert does not assign a free dessert when the order is not steak with caesar salad and mixed drink, nor lobster with green salad and wine. This exercises the requirement that only those two combinations qualify for a free dessert, and all other combinations do not result in a free dessert being set.
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:CHICKEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:CAESAR
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:MIXED_DRINK
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Steak_Caesar_MixedDrink_Qualifies_For_Pie-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR27
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that when an order consists of steak, caesar salad, and a mixed drink, the system sets the dessert to pie as a free dessert per FR27.1.
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:STEAK
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:CAESAR
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:MIXED_DRINK
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:PIE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Party_To_Waiting_List
TEST.NEW
TEST.NAME:Test_Waiting_List_Maximum_Capacity-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR23
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that the waiting list supports up to 10 parties by adding a party when the list is at its maximum capacity (index 9), ensuring the 10th slot is used and the size is incremented correctly.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingListSize:9
TEST.VALUE:manager.Add_Party_To_Waiting_List.Name:"PartyTen"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingList[9]:"PartyTen"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListSize:10
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Party_To_Waiting_List
TEST.NEW
TEST.NAME:Test_Add_Party_To_Waiting_List_By_Name-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR24
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that a party can be added to the waiting list by specifying its name, and that the name is correctly stored in the next available slot.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingListSize:0
TEST.VALUE:manager.Add_Party_To_Waiting_List.Name:"Smith"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingList[0]:"Smith"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListSize:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Check_Total
TEST.NEW
TEST.NAME:Get_Check_Total_Returns_Correct_Check_Total_For_Table-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR22
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

This test verifies that Get_Check_Total returns the correct check total for a given table by stubbing Get_Table_Record to return a table record with a known Check_Total value. This directly exercises the requirement that the system provides a way to obtain the check total for a given table.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.VALUE:manager.Get_Check_Total.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:manager.Get_Check_Total.return:123.45
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Clear_Table_Sets_Check_Total_To_Zero-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR21
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

This test verifies that calling Clear_Table on a table sets the table's check total to 0.0 in the table database by checking the value passed to Update_Table_Record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:0.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Next_Party_To_Be_Seated
TEST.NEW
TEST.NAME:Get_Head_Of_Waiting_List_Returns_Correct_Name-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR25
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that Get_Next_Party_To_Be_Seated returns the name of the party at the head of the waiting list (index 0) and increments the index. This exercises the system's ability to provide the name at the head of the waiting list.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingListIndex:0
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[0]:"Smith"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[1]:"Johnson"
TEST.EXPECTED:manager.Get_Next_Party_To_Be_Seated.return:"Smith"
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Next_Party_To_Be_Seated
TEST.NEW
TEST.NAME:WaitingListIndex_Resets_When_At_End_Of_List-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR26
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that when the WaitingListIndex exceeds 9, it is reset to 0 and the head of the waiting list is returned from index 0. This ensures the head of the waiting list is reset when reaching the end.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingListIndex:10
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[0]:"Anderson"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[9]:"Williams"
TEST.EXPECTED:manager.Get_Next_Party_To_Be_Seated.return:"Anderson"
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Lobster_Green_Wine_Qualifies_For_Cake-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR27
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that when an order consists of lobster, green salad, and wine, the system sets the dessert to cake as a free dessert per FR27.2.
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:LOBSTER
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:GREEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:WINE
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:CAKE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_None_Order_Does_Not_Increase_Check-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR17
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that placing an order for no entree does not increase the table's check total. The initial check total is set to 15.0, and after placing the order, it should remain 15.0. This exercises FR17.5.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:NO_ENTREE
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:15.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:15.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Updates_Occupied_Status_To_False-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR18
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Verifies that after calling Clear_Table, the table's occupied status is set to false (v_false) in the table database, as required by FR18.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:99.99
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Table:2
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Is_Occupied:0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Accepts_All_Six_Table_Indices-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR11
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Verifies that Clear_Table can be called for all six supported table indices (0 to 5), as required by FR11.1. This test uses table index 5 (the highest valid index) to ensure the function supports the full range.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.VALUE:manager.Clear_Table.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'E'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:manager.Clear_Table.return:0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Clear_Table_Clears_All_Orders_For_All_Seats-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR20
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that calling Clear_Table sets all order fields (Soup, Salad, Entree, Dessert, Beverage) to their NO_* values for all seats in the updated table record, as required by FR20.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:50.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Beverage:NO_BEVERAGE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Clear_Table_Sets_Number_In_Party_To_One-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR19
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that calling Clear_Table sets the Number_In_Party field to 1 in the updated table record, as required by FR19.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Table:2
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Number_In_Party:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Place_Order_Supports_All_Entree_Types-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR13
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Verifies that Place_Order accepts all supported entree types (steak, chicken, lobster, pasta, none) by placing an order for each entree at seat 0 and checking the correct update to the table record. This exercises the system's support for all specified entrees as required by FR13.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:0
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:0.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Entree:STEAK
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:14.0
TEST.EXPECTED:manager.Place_Order.return:0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Place_Order_Supports_4_Seats_Per_Table-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR12
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Verifies that Place_Order can handle all 4 seats (0-3) for a table by placing an order at seat 3, the highest valid seat index. This exercises the system's support for 4 seats per table as required by FR12.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:1
TEST.VALUE:manager.Place_Order.Seat:3
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Table:1
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Entree:STEAK
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Number_In_Party:3
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Is_Occupied:v_true
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:34.0
TEST.EXPECTED:manager.Place_Order.return:0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Table_Number_In_Party_Incremented_On_Order-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR15
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that placing an order increments the table's number in party in the table database. The test simulates placing an order for seat 2 at table 3, where the table previously had 2 people in the party. The expected result is that Update_Table_Record is called with Number_In_Party set to 3.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:3
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:ONION
TEST.VALUE:manager.Place_Order.Order.Salad:GREEN
TEST.VALUE:manager.Place_Order.Order.Entree:CHICKEN
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Number_In_Party:3
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Table_Occupied_Status_Updated_On_Order-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR14
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that placing an order sets the table's occupied status to true in the table database. The test simulates placing an order for seat 1 at table 2, where the table was previously unoccupied. The expected result is that Update_Table_Record is called with Is_Occupied set to v_true.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:0.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Is_Occupied:v_true
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Seat_Order_Updated_In_Table-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR16
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that placing an order updates the seat's order in the table database. The test sets up a table with a known order for seat 2, then places a new order for seat 2 and checks that Update_Table_Record is called with the new order for that seat, while other seats remain unchanged.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:5
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:ONION
TEST.VALUE:manager.Place_Order.Order.Salad:CAESAR
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Table:5
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Soup:ONION
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Salad:CAESAR
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Entree:STEAK
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Dessert:PIE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Beverage:MIXED_DRINK
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Steak_Order_Increases_Check_Total_By_14-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR17
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that placing an order for steak increases the table's check total by 14.0. The test sets up a table with a known check total, places a steak order, and checks that Update_Table_Record is called with the check total increased by 14.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:3
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:CAESAR
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:50.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Table:3
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:64.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Place_Order_Check_Total_Increase_For_Lobster-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR17
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that placing an order for lobster increases the table's check total by 18.0. The test sets up a table with a known check total, places a lobster order, and verifies that the check total is increased by 18.0 in the updated table record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:3
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:LOBSTER
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:50.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:68.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Place_Order_Check_Total_Increase_For_Chicken-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR17
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that placing an order for chicken increases the table's check total by 10.0. The test sets up a table with a known check total, places a chicken order, and verifies that the check total is increased by 10.0 in the updated table record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:CHICKEN
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:25.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:35.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Pasta_Order_Increases_Check_By_12-REVIEW-NEEDED
TEST.REQUIREMENT_KEY:FR17
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tests that placing an order for pasta increases the table's check total by 12.0. The initial check total is set to 20.0, and after placing the order, it should be 32.0. This exercises FR17.4.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:1
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:PASTA
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:32.0
TEST.END

