TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Party_To_Waiting_List
TEST.NEW
TEST.NAME:Test_Add_Party_To_WaitingList_ByName-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR24

Verifies that a party can be added to the waiting list by specifying its name. Adds a party named 'Smith' to an empty waiting list and checks that the name is stored at index 0 and the size is incremented.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingListSize:0
TEST.VALUE:manager.Add_Party_To_Waiting_List.Name:"Smith"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingList[0]:"Smith"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListSize:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Check_Total
TEST.NEW
TEST.NAME:Get_Check_Total_Returns_Correct_Check_Total_For_Table-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR22

This test verifies that Get_Check_Total returns the correct check total for a given table by stubbing Get_Table_Record to return a table_data_type with a known Check_Total value. This directly exercises the requirement that the system provides a way to obtain the check total for a given table.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.VALUE:manager.Get_Check_Total.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:manager.Get_Check_Total.return:123.45
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Party_To_Waiting_List
TEST.NEW
TEST.NAME:Test_WaitingList_Maximum_Capacity-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR23

Verifies that the waiting list supports up to 10 parties. Adds a party when the list is at its maximum index (9), ensuring the party is added at the last slot and the size increments to 10.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingListSize:9
TEST.VALUE:manager.Add_Party_To_Waiting_List.Name:"PartyTen"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingList[9]:"PartyTen"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListSize:10
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Clear_Table_Sets_Check_Total_To_Zero-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR21

This test verifies that calling Clear_Table sets the table's check total to 0.0 in the table database, as required by FR21.1. The test stubs Get_Table_Record to return a table with a nonzero check total, and expects Update_Table_Record to be called with a check total of 0.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Table:2
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Steak_Caesar_MixedDrink_Qualifies_For_Pie-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR27

Tests that when an order consists of steak, caesar salad, and a mixed drink, the system qualifies the seat for a free pie dessert by setting Dessert to PIE.
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:STEAK
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:CAESAR
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:MIXED_DRINK
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:PIE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Lobster_Green_Wine_Qualifies_For_Cake-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR27

Tests that when an order consists of lobster, green salad, and wine, the system qualifies the seat for a free cake dessert by setting Dessert to CAKE.
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:LOBSTER
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:GREEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:WINE
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:CAKE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Other_Order_Does_Not_Qualify_For_Free_Dessert-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR27

Tests that when an order does not match either the steak/caesar/mixed drink or lobster/green/wine combinations, the system does not qualify the seat for any free dessert (Dessert remains unchanged).
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:CHICKEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:GREEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:SODA
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Next_Party_To_Be_Seated
TEST.NEW
TEST.NAME:WaitingListIndex_Resets_When_At_End_Of_List-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR26

Tests that when WaitingListIndex is greater than 9, Get_Next_Party_To_Be_Seated resets the index to 0 and returns the name at the head of the waiting list. This exercises the requirement FR26.1 that the head of the waiting list is reset when it reaches the end.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[0]:"Smith"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[1]:"Johnson"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[2]:"Williams"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[3]:"Brown"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[4]:"Jones"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[5]:"Garcia"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[6]:"Miller"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[7]:"Davis"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[8]:"Rodriguez"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[9]:"Martinez"
TEST.VALUE:manager.<<GLOBAL>>.WaitingListIndex:10
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListIndex:1
TEST.EXPECTED:manager.Get_Next_Party_To_Be_Seated.return:"Smith"
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Next_Party_To_Be_Seated
TEST.NEW
TEST.NAME:Get_Head_Of_Waiting_List_Returns_Correct_Name-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR25

Tests that Get_Next_Party_To_Be_Seated returns the name of the party at the head of the waiting list (index 0) and increments the index. This exercises the system's ability to provide the name at the head of the waiting list as required by FR25.1.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[0]:"Smith"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[1]:"Johnson"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[2]:"Williams"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[3]:"Brown"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[4]:"Jones"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[5]:"Garcia"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[6]:"Miller"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[7]:"Davis"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[8]:"Rodriguez"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[9]:"Martinez"
TEST.VALUE:manager.<<GLOBAL>>.WaitingListIndex:0
TEST.EXPECTED:manager.Get_Next_Party_To_Be_Seated.return:"Smith"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListIndex:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Pasta_Order_Increases_Check_Total_By_12-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order for pasta increases the table's check total by 12.0. The initial check total is set to 20.0, and after placing the order, it should be 32.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:1
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:PASTA
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:32.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_None_Entree_Order_Does_Not_Change_Check_Total-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order with no entree does not change the table's check total. The initial check total is set to 15.0, and after placing the order, it should remain 15.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:NO_ENTREE
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:15.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:15.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Sets_Is_Occupied_False-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR18

Verifies that after clearing a table, the Update_Table_Record is called with Is_Occupied set to v_false, as required by FR18.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Jones"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:99.99
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Is_Occupied:0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Clears_All_Orders-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR20

Verifies that after clearing a table, the Update_Table_Record is called with all Order fields for all seats set to NO_SOUP, NO_SALAD, NO_ENTREE, NO_DESSERT, and NO_BEVERAGE, as required by FR20.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'D'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Kim"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:77.77
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Beverage:NO_BEVERAGE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Supports_All_Six_Tables-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR11

Verifies that Clear_Table can be called for all six supported table indices (0 to 5), as required by FR11.1. This test uses table index 5 (the highest valid index) to ensure the function supports the full range.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Smith"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:manager.Clear_Table.return:0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Table:5
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Sets_Number_In_Party_To_One-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR19

Verifies that after clearing a table, the Update_Table_Record is called with Number_In_Party set to 1, as required by FR19.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'C'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Lee"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:55.55
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Number_In_Party:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Order_Updates_Seat_Order-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR16

Tests that placing an order updates the correct seat's order in the table database. The test sets up a table with 2 seats, places an order for seat 1, and checks that only seat 1's order is updated in the call to Update_Table_Record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:5
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:ONION
TEST.VALUE:manager.Place_Order.Order.Salad:CAESAR
TEST.VALUE:manager.Place_Order.Order.Entree:CHICKEN
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:0.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Soup:ONION
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Salad:CAESAR
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Entree:CHICKEN
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Beverage:SODA
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Steak_Order_Increases_Check_Total_By_14-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order for steak increases the table's check total by 14.0. The test sets up a table with a check total of 20.0, places a steak order, and expects the updated check total to be 34.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:0
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:34.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Lobster_Order_Increases_Check_Total_By_18-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order for lobster increases the table's check total by 18.0. The test sets up a table with a check total of 50.0, places a lobster order, and expects the updated check total to be 68.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:7
TEST.VALUE:manager.Place_Order.Seat:3
TEST.VALUE:manager.Place_Order.Order.Soup:CHOWDER
TEST.VALUE:manager.Place_Order.Order.Salad:GREEN
TEST.VALUE:manager.Place_Order.Order.Entree:LOBSTER
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:7
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'D'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Diana"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:50.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:68.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Chicken_Order_Increases_Check_Total_By_10-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order for chicken increases the table's check total by 10.0. The test sets up a table with a check total of 5.0, places a chicken order, and expects the updated check total to be 15.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:3
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:GREEN
TEST.VALUE:manager.Place_Order.Order.Entree:CHICKEN
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'C'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Carol"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:5.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:15.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Number_In_Party_Incremented-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR15

Verifies that placing an order increments the table's number in party in the table database.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:7
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:CHOWDER
TEST.VALUE:manager.Place_Order.Order.Salad:GREEN
TEST.VALUE:manager.Place_Order.Order.Entree:PASTA
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:7
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'D'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Tom"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Number_In_Party:4
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Table_Supports_4_Seats-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR12

Verifies that the system supports 4 seats per table by placing orders for all 4 seats and checking that the correct seat's order is updated in the table data.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:1
TEST.VALUE:manager.Place_Order.Seat:3
TEST.VALUE:manager.Place_Order.Order.Soup:ONION
TEST.VALUE:manager.Place_Order.Order.Salad:CAESAR
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:0.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Soup:ONION
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Salad:CAESAR
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Entree:STEAK
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Dessert:PIE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Beverage:MIXED_DRINK
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Table_Occupied_Status_Updated-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR14

Verifies that placing an order updates the table's occupied status to true in the table database.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:5
TEST.VALUE:manager.Place_Order.Seat:0
TEST.VALUE:manager.Place_Order.Order.Soup:CHOWDER
TEST.VALUE:manager.Place_Order.Order.Salad:GREEN
TEST.VALUE:manager.Place_Order.Order.Entree:CHICKEN
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'C'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Ann"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:0.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Is_Occupied:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Support_Lobster_Entree-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR13

Test that Place_Order supports the 'lobster' entree by verifying the check total is updated correctly when ordering lobster.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:1
TEST.VALUE:manager.Place_Order.Seat:0
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:LOBSTER
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:50.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:68.0
TEST.END

