TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Party_To_Waiting_List
TEST.NEW
TEST.NAME:Test_WaitingList_Maximum_Capacity-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR23

Tests that the waiting list supports up to 10 parties by adding a party when the list is at its maximum capacity (index 9). The function should reset WaitingListSize to 0 if it exceeds 9, allowing the new party to be added at index 0.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingListSize:10
TEST.VALUE:manager.Add_Party_To_Waiting_List.Name:"Smith"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingList[0]:"Smith"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListSize:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Party_To_Waiting_List
TEST.NEW
TEST.NAME:Test_Add_Party_To_Waiting_List_By_Name-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR24

Tests that a party can be added to the waiting list by specifying its name. The name should be copied into the next available slot, and WaitingListSize should increment.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingListSize:0
TEST.VALUE:manager.Add_Party_To_Waiting_List.Name:"Johnson"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingList[0]:"Johnson"
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListSize:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Check_Total
TEST.NEW
TEST.NAME:Get_Check_Total_Returns_Correct_Check_Total_For_Table-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR22

This test verifies that the Get_Check_Total function returns the correct check total for a given table by stubbing Get_Table_Record to return a table_data_type with a known Check_Total value. This directly exercises the requirement that the system provides a way to obtain the check total for a given table.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.VALUE:manager.Get_Check_Total.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:manager.Get_Check_Total.return:123.45
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Clear_Table_Sets_Check_Total_To_Zero-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR21

This test verifies that calling Clear_Table sets the table's check total to 0.0 in the table database by checking the value passed to Update_Table_Record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Table:2
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Next_Party_To_Be_Seated
TEST.NEW
TEST.NAME:WaitingListIndex_Reset_After_End-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR26

Tests that when the waiting list index exceeds the last entry (index 9), it is reset to 0 and the head of the waiting list is returned from the start.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[0]:"Alice"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[1]:"Bob"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[2]:"Carol"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[3]:"Dave"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[4]:"Eve"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[5]:"Frank"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[6]:"Grace"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[7]:"Heidi"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[8]:"Ivan"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[9]:"Judy"
TEST.VALUE:manager.<<GLOBAL>>.WaitingListIndex:10
TEST.EXPECTED:manager.<<GLOBAL>>.WaitingListIndex:1
TEST.EXPECTED:manager.Get_Next_Party_To_Be_Seated.return:"Alice"
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Get_Next_Party_To_Be_Seated
TEST.NEW
TEST.NAME:Get_Head_Of_WaitingList_Returns_FirstParty-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR25

Tests that Get_Next_Party_To_Be_Seated returns the name of the party at the head of the waiting list (index 0) when the waiting list index is at the start.
TEST.END_NOTES:
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[0]:"Alice"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[1]:"Bob"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[2]:"Carol"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[3]:"Dave"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[4]:"Eve"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[5]:"Frank"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[6]:"Grace"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[7]:"Heidi"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[8]:"Ivan"
TEST.VALUE:manager.<<GLOBAL>>.WaitingList[9]:"Judy"
TEST.VALUE:manager.<<GLOBAL>>.WaitingListIndex:0
TEST.EXPECTED:manager.Get_Next_Party_To_Be_Seated.return:"Alice"
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Other_Order_Does_Not_Qualify_For_Free_Dessert-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR27

Tests that when an order does not match either the steak/caesar/mixed drink or lobster/green/wine combinations, the system does not qualify the seat for any free dessert (Dessert remains unchanged).
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:CHICKEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:GREEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:SODA
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Lobster_Green_Wine_Qualifies_For_Cake-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR27

Tests that when an order consists of lobster, green salad, and wine, the system qualifies the seat for a free cake dessert by setting Dessert to CAKE.
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:LOBSTER
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:GREEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:WINE
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:CAKE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Steak_Caesar_MixedDrink_Qualifies_For_Pie-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR27

Tests that when an order consists of steak, caesar salad, and a mixed drink, the system qualifies the seat for a free pie dessert by setting Dessert to PIE.
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:STEAK
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:CAESAR
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:MIXED_DRINK
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Soup:NO_SOUP
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:PIE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Pasta_Order_Increases_Check_Total_By_12-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order for pasta increases the table's check total by 12.0. The test sets up a table with an initial check total, places a pasta order, and verifies that the check total is incremented by 12.0 in the updated table record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:1
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:PASTA
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:32.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_None_Entree_Order_Does_Not_Change_Check_Total-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order with no entree (NO_ENTREE) does not increase the table's check total. The test sets up a table with an initial check total, places a NO_ENTREE order, and verifies that the check total remains unchanged in the updated table record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:NO_ENTREE
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:15.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:15.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_All_Entree_Types_Supported-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR13

Verifies that the system supports all specified entree types by placing an order for each entree and checking the correct entree is set in the table record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:LOBSTER
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Sue"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Entree:LOBSTER
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Table_Occupied_Status_Updated-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR14

Checks that placing an order sets the table's occupied status to true in the table database.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:5
TEST.VALUE:manager.Place_Order.Seat:0
TEST.VALUE:manager.Place_Order.Order.Soup:ONION
TEST.VALUE:manager.Place_Order.Order.Salad:GREEN
TEST.VALUE:manager.Place_Order.Order.Entree:CHICKEN
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'C'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Ann"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:0.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Is_Occupied:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Number_In_Party_Incremented-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR15

Ensures that placing an order increments the table's number in party in the table database.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:7
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:CHOWDER
TEST.VALUE:manager.Place_Order.Order.Salad:CAESAR
TEST.VALUE:manager.Place_Order.Order.Entree:PASTA
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:7
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'D'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Joe"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:5.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Number_In_Party:4
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Four_Seats_Per_Table-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR12

Verifies that the system supports 4 seats per table by placing orders at all four seat indices (0 to 3) and ensuring each seat's order is updated in the table record.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:1
TEST.VALUE:manager.Place_Order.Seat:3
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:NO_SALAD
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:0
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:0.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Entree:STEAK
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Seat_Order_Updated_On_Place_Order-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR16

Tests that placing an order updates the seat's order in the table database. The test sets up a table with no orders, places a new order for seat 2, and checks that Update_Table_Record is called with the correct order for that seat.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:1
TEST.VALUE:manager.Place_Order.Seat:2
TEST.VALUE:manager.Place_Order.Order.Soup:ONION
TEST.VALUE:manager.Place_Order.Order.Salad:GREEN
TEST.VALUE:manager.Place_Order.Order.Entree:CHICKEN
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_false
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Alice"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:0.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Soup:ONION
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Salad:GREEN
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Entree:CHICKEN
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Beverage:SODA
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Check_Total_Updated_For_Lobster_Order-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order for lobster increases the table's check total by 18.0. The test sets up a table with a known check total, places a lobster order, and checks that Update_Table_Record is called with the check total increased by 18.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:4
TEST.VALUE:manager.Place_Order.Seat:3
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:GREEN
TEST.VALUE:manager.Place_Order.Order.Entree:LOBSTER
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'D'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Dave"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:50.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:68.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Check_Total_Updated_For_Chicken_Order-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order for chicken increases the table's check total by 10.0. The test sets up a table with a known check total, places a chicken order, and checks that Update_Table_Record is called with the check total increased by 10.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:3
TEST.VALUE:manager.Place_Order.Seat:0
TEST.VALUE:manager.Place_Order.Order.Soup:CHOWDER
TEST.VALUE:manager.Place_Order.Order.Salad:CAESAR
TEST.VALUE:manager.Place_Order.Order.Entree:CHICKEN
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'C'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Carol"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:5.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:15.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Place_Order
TEST.NEW
TEST.NAME:Test_Check_Total_Updated_For_Steak_Order-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR17

Tests that placing an order for steak increases the table's check total by 14.0. The test sets up a table with a known check total, places a steak order, and checks that Update_Table_Record is called with the check total increased by 14.0.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Place_Order.Table:2
TEST.VALUE:manager.Place_Order.Seat:1
TEST.VALUE:manager.Place_Order.Order.Soup:NO_SOUP
TEST.VALUE:manager.Place_Order.Order.Salad:CAESAR
TEST.VALUE:manager.Place_Order.Order.Entree:STEAK
TEST.VALUE:manager.Place_Order.Order.Dessert:NO_DESSERT
TEST.VALUE:manager.Place_Order.Order.Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:v_true
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Bob"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:NO_ENTREE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:NO_BEVERAGE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:20.0
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Check_Total:34.0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Updates_Number_In_Party_To_One-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR19

Verifies that after clearing a table, the Update_Table_Record is called with Number_In_Party set to 1, as required by FR19.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'C'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Lee"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:55.55
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Number_In_Party:1
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Updates_Occupied_Status_To_False-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR18

Verifies that after clearing a table, the Update_Table_Record is called with Is_Occupied set to v_false, as required by FR18.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:3
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'B'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Jones"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:99.99
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Is_Occupied:0
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Clears_All_Orders-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR20

Verifies that after clearing a table, the Update_Table_Record is called with all Order fields for all seats set to NO_SOUP, NO_SALAD, NO_ENTREE, NO_DESSERT, and NO_BEVERAGE, as required by FR20.1.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.STUB:uut_prototype_stubs.Update_Table_Record
TEST.VALUE:manager.Clear_Table.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:2
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'D'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Kim"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:77.77
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[0].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[1].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[2].Beverage:NO_BEVERAGE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Soup:NO_SOUP
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Salad:NO_SALAD
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Entree:NO_ENTREE
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Dessert:NO_DESSERT
TEST.EXPECTED:uut_prototype_stubs.Update_Table_Record.Data.Order[3].Beverage:NO_BEVERAGE
TEST.END

TEST.UNIT:manager
TEST.SUBPROGRAM:Clear_Table
TEST.NEW
TEST.NAME:Test_Clear_Table_Supports_All_6_Tables-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: FR11

Verifies that Clear_Table can be called for all 6 supported table indices (0 to 5) as required by FR11.1. This test uses table index 5 (the highest valid index) to ensure the function supports the full range.
TEST.END_NOTES:
TEST.STUB:uut_prototype_stubs.Get_Table_Record
TEST.VALUE:manager.Clear_Table.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.Table:5
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Is_Occupied:1
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Number_In_Party:4
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Designator:'A'
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Wait_Person:"Smith"
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Soup:ONION
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Salad:CAESAR
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Entree:STEAK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Dessert:CAKE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[0].Beverage:WINE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Soup:CHOWDER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Salad:GREEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Entree:CHICKEN
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Dessert:PIE
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[1].Beverage:BEER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Entree:LOBSTER
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Dessert:FRUIT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[2].Beverage:MIXED_DRINK
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Soup:NO_SOUP
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Salad:NO_SALAD
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Entree:PASTA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Dessert:NO_DESSERT
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Order[3].Beverage:SODA
TEST.VALUE:uut_prototype_stubs.Get_Table_Record.return.Check_Total:123.45
TEST.EXPECTED:manager.Clear_Table.return:0
TEST.END

