TEST.UNIT:manager
TEST.SUBPROGRAM:Add_Included_Dessert
TEST.NEW
TEST.NAME:Test_Lobster_Green_Wine_Results_In_Cake_Dessert-REVIEW-NEEDED
TEST.NOTES:
WARNING: This test case was generated by an AI-based system. Please review it carefully.

Tested Requirement ID: Add_Included_Dessert.2

Tests that Add_Included_Dessert sets Dessert to CAKE when Entree is LOBSTER, Salad is GREEN, and Beverage is WINE, as required.
TEST.END_NOTES:
TEST.VALUE:manager.Add_Included_Dessert.Order:<<malloc 1>>
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Entree:LOBSTER
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Salad:GREEN
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Beverage:WINE
TEST.VALUE:manager.Add_Included_Dessert.Order[0].Dessert:NO_DESSERT
TEST.EXPECTED:manager.Add_Included_Dessert.Order[0].Dessert:CAKE
TEST.END

