name: Vector Vscode Vcast Tests
run-name: ${{ github.actor }} is testing Vector Vscode Vcast
on: [push]
jobs:
  test:
    runs-on: [self-hosted, vscode-vcast]

    container:
      image: rds-vtc-docker-dev-local.vegistry.vg.vector.int/vcast/vcast_base:latest
      options: --user root

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Package with VSCE
        run: vsce package

      - name: Run tests
        run: npm test