name: Vector Vscode Vcast Tests
run-name: ${{ github.ref_name }} is being tested
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
  workflow_dispatch:
jobs:
  test:
    permissions: write-all
    runs-on: [self-hosted, vscode-vcast]

    container:
      image: rds-vtc-docker-dev-local.vegistry.vg.vector.int/vcast/vcast_base
      options: --user vcast_user

    steps:
      - name: Start forward proxy
        run: |
          sudo /usr/sbin/squid
          NEW_PROXY="http://$(hostname --ip-address):3128"
          echo "HTTP_PROXY=$NEW_PROXY" >> $GITHUB_ENV
          echo "HTTPS_PROXY=$NEW_PROXY" >> $GITHUB_ENV
          echo "http_proxy=$NEW_PROXY" >> $GITHUB_ENV
          echo "https_proxy=$NEW_PROXY" >> $GITHUB_ENV
          echo "GLOBAL_AGENT_HTTP_PROXY=$NEW_PROXY" >> $GITHUB_ENV
          echo "GLOBAL_AGENT_HTTPS_PROXY=$NEW_PROXY" >> $GITHUB_ENV

      - name: Show image
        run: |
          curl -H "X-JFrog-Art-Api:${{ secrets.ARTIFACTORY_TOKEN }}" -O https://artifactory.vi.vector.int/artifactory/rds-build-packages-generic-dev/vscode/tests-results/main/2024-06-24T16%3A53%3A05-b277b82ffcf98ced2348e19f6db0d550e0a6aa49/e2e_vcast23_screenshots/error%20in%20test%205%20should%20validate%20test%20deletion.png

      - name: Encode image to base64
        id: encode_image
        run: |
          base64 error%20in%20test%205%20should%20validate%20test%20deletion.png > error%20in%20test%205%20should%20validate%20test%20deletion.base64
          echo "encoded_image=$(cat error%20in%20test%205%20should%20validate%20test%20deletion.base64)" >> $GITHUB_STATE
      
      - name: Create summary with image
        run: |
          echo "![Test image](data:image/png;base64,${{ env.STATE_encoded_image }})" >> $GITHUB_STEP_SUMMARY
